import type { JobOpening } from "@/types";

export const jobOpenings: JobOpening[] = [
  {
    id: "1",
    title: "Senior AI/ML Engineer",
    department: "AI & Research",
    location: "Mumbai, India (Hybrid)",
    type: "full-time",
    experience: "3–6 years",
    description:
      "We're looking for an AI/ML Engineer who's built and shipped real production AI systems — not just run notebooks. You'll work directly on client-facing AI projects, designing everything from the data pipeline to the inference layer.",
    responsibilities: [
      "Design and implement end-to-end ML pipelines from data ingestion to model deployment",
      "Fine-tune large language models (LLMs) for domain-specific enterprise applications",
      "Build RAG systems using vector databases and embedding models",
      "Collaborate with product and engineering teams to translate business requirements into ML solutions",
      "Monitor and optimize deployed models for performance, drift, and cost",
      "Write clean, well-documented Python code that a team can maintain",
    ],
    requirements: [
      "3+ years of hands-on ML/AI engineering experience (not just academic)",
      "Strong Python; proficient in PyTorch or TensorFlow",
      "Experience with LLMs, prompt engineering, and at least one RAG implementation",
      "Familiarity with MLOps: model versioning, deployment, monitoring",
      "Experience with vector databases (Pinecone, Chroma, Weaviate)",
      "Understanding of distributed systems and cloud infrastructure (AWS/GCP preferred)",
    ],
    niceToHave: [
      "Experience fine-tuning models with PEFT/LoRA",
      "LangChain or LlamaIndex experience",
      "Background in NLP for Indian languages",
    ],
    postedAt: "2025-11-01",
  },
  {
    id: "2",
    title: "Senior Full-Stack Engineer (Next.js / TypeScript)",
    department: "Engineering",
    location: "Mumbai, India (Hybrid)",
    type: "full-time",
    experience: "3–5 years",
    description:
      "You'll build high-performance web applications for clients ranging from VC-backed startups to enterprise companies. You care deeply about performance, accessibility, and code quality — and you have the TypeScript chops to back it up.",
    responsibilities: [
      "Design and build full-stack web applications using Next.js, TypeScript, and Node.js",
      "Architect scalable APIs and data models for complex business domains",
      "Implement best-in-class performance optimizations (Core Web Vitals, bundle splitting)",
      "Collaborate with designers to implement pixel-perfect, accessible UIs",
      "Code review for junior engineers — raise the floor, not just the ceiling",
      "Contribute to and help maintain our internal component library",
    ],
    requirements: [
      "3+ years of production Next.js or React experience",
      "Strong TypeScript — you don't reach for 'any'",
      "Experience with SQL and NoSQL databases",
      "Solid understanding of REST API design",
      "Experience with CI/CD pipelines",
      "Lighthouse scores matter to you — you can explain why",
    ],
    niceToHave: [
      "Experience with GSAP or Framer Motion for complex animations",
      "Contribution to open-source projects",
      "Full-stack experience including infrastructure (Docker, AWS)",
    ],
    postedAt: "2025-11-01",
  },
  {
    id: "3",
    title: "Product Designer (UX/UI)",
    department: "Design",
    location: "Mumbai, India (Hybrid)",
    type: "full-time",
    experience: "2–5 years",
    description:
      "You'll shape the end-to-end user experience for digital products across industries. You're as comfortable facilitating a discovery workshop as you are pixel-pushing in Figma. And you understand that beautiful design that doesn't convert isn't good design.",
    responsibilities: [
      "Lead UX research: user interviews, usability testing, heuristic evaluations",
      "Create user flows, information architecture, wireframes, and high-fidelity prototypes",
      "Build and maintain design systems in Figma with Figma Variables",
      "Collaborate with engineers in design-to-code handoffs that actually work",
      "Define interaction design: micro-animations, state transitions, error handling",
      "Champion accessibility throughout the design process",
    ],
    requirements: [
      "2+ years of product design experience (SaaS, mobile app, or enterprise software preferred)",
      "Figma proficiency — auto-layout, components, variables",
      "A portfolio that demonstrates UX thinking, not just visual skill",
      "Experience designing for mobile (iOS/Android conventions)",
      "Understanding of web/app implementation constraints",
    ],
    niceToHave: [
      "Motion design experience (Principle, Jitter, or code-level animation)",
      "Design system building experience",
      "User research facilitation background",
    ],
    postedAt: "2025-10-15",
  },
  {
    id: "4",
    title: "React Native Mobile Engineer",
    department: "Engineering",
    location: "Mumbai, India (Remote eligible)",
    type: "full-time",
    experience: "2–4 years",
    description:
      "You'll build mobile apps that millions of users across India will rely on daily — in healthcare, fintech, e-commerce, and logistics. You care about native performance, app store compliance, and the UX details that make users come back.",
    responsibilities: [
      "Build cross-platform mobile apps in React Native and Expo",
      "Integrate with REST APIs, GraphQL endpoints, and native device APIs",
      "Implement push notification strategies for engagement campaigns",
      "Handle app store submission and ASO for both iOS and Android",
      "Implement offline-first architecture with local state persistence",
      "Work with designers to achieve native-quality animations and transitions",
    ],
    requirements: [
      "2+ years of React Native production experience",
      "Submitted at least one app to the App Store and Play Store",
      "Strong JavaScript/TypeScript fundamentals",
      "Understanding of React Native performance optimization (Hermes, Reanimated)",
      "Experience with mobile state management (Redux, Zustand, or React Query)",
    ],
    niceToHave: [
      "Expo EAS Build and submit experience",
      "Native module development (Swift/Kotlin basics)",
      "Experience with React Native Reanimated 2/3",
    ],
    postedAt: "2025-10-01",
  },
  {
    id: "5",
    title: "DevOps / Cloud Engineer",
    department: "Infrastructure",
    location: "Mumbai, India (Remote eligible)",
    type: "full-time",
    experience: "3–6 years",
    description:
      "You'll design and operate the cloud infrastructure that powers products used by thousands of users daily. You believe in infrastructure as code, blameless postmortems, and observability from day one — not as an afterthought.",
    responsibilities: [
      "Design and implement cloud architecture on AWS (primary), GCP, or Azure",
      "Build and maintain CI/CD pipelines using GitHub Actions and Argo CD",
      "Manage Kubernetes clusters, deployment strategies, and service mesh",
      "Implement Infrastructure as Code with Terraform and Helm",
      "Build observability stacks: metrics (Prometheus/Grafana), logging, tracing",
      "Security posture management: IAM, secrets, compliance automation",
    ],
    requirements: [
      "3+ years of DevOps/cloud engineering experience",
      "AWS Solutions Architect or equivalent practical experience",
      "Kubernetes in production — not just local Minikube",
      "Terraform for infrastructure management",
      "GitHub Actions or equivalent CI/CD pipeline experience",
      "Linux fundamentals: networking, permissions, process management",
    ],
    niceToHave: [
      "AWS certifications (SAA, SAP, DevOps Professional)",
      "Service mesh experience (Istio, Linkerd)",
      "Cost optimization experience (FinOps)",
    ],
    postedAt: "2025-09-15",
  },
  {
    id: "6",
    title: "Business Development Manager",
    department: "Sales",
    location: "Mumbai, India",
    type: "full-time",
    experience: "3–5 years",
    description:
      "You'll be the face of Axen Technology for enterprise and mid-market clients across India. You understand technology deeply enough to have credible technical conversations — and you know how to translate that into business value that drives decisions.",
    responsibilities: [
      "Identify, qualify, and close new enterprise and mid-market technology engagements",
      "Own the full sales cycle from first call to signed SOW",
      "Develop and maintain relationships with CXOs, VPs, and technology decision-makers",
      "Collaborate with delivery teams to scope projects and create proposals",
      "Represent Axen at industry events, conferences, and networking forums",
      "Maintain accurate pipeline in CRM and forecast accurately",
    ],
    requirements: [
      "3+ years of B2B technology sales experience",
      "Comfortable discussing AI, web/mobile development, and cloud services at a technical level",
      "Track record of closing deals ₹20L+ in value",
      "Strong presentation and communication skills in English and Hindi",
      "Experience selling to enterprise or mid-market companies in India",
    ],
    niceToHave: [
      "Network in tech-adjacent sectors: fintech, healthcare, e-commerce",
      "Experience with account-based selling methodologies",
    ],
    postedAt: "2025-09-01",
  },
];
