import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: "ai-solutions",
    slug: "ai-solutions",
    title: "AI Solutions",
    shortTitle: "AI Solutions",
    description:
      "Harness the transformative power of artificial intelligence to automate operations, unlock insights from your data, and create experiences that feel genuinely intelligent. From GPT-powered chatbots to custom machine learning models trained on your business data, we engineer AI that delivers measurable ROI.",
    shortDescription:
      "Custom AI, machine learning, and automation solutions that give your business a decisive competitive edge.",
    icon: "Brain",
    color: "#CC0000",
    badge: "HOT",
    features: [
      "AI Consulting & Strategy",
      "Generative AI Development",
      "AI Chatbots & Virtual Assistants",
      "Machine Learning Model Development",
      "Business Process Automation",
      "Computer Vision Solutions",
      "Predictive Analytics",
      "Natural Language Processing",
      "AI Integration & APIs",
      "MLOps & Model Deployment",
    ],
    benefits: [
      "Reduce operational costs by up to 40% through intelligent automation",
      "Make faster, more accurate decisions with predictive analytics",
      "Scale customer support without scaling headcount",
      "Uncover revenue opportunities hidden in your data",
      "Future-proof your business with enterprise-grade AI infrastructure",
    ],
    techStack: [
      "OpenAI GPT-4",
      "LangChain",
      "TensorFlow",
      "PyTorch",
      "Hugging Face",
      "FastAPI",
      "Python",
      "AWS SageMaker",
      "Pinecone",
      "Redis",
    ],
    process: [
      {
        step: 1,
        title: "Data Assessment",
        description:
          "We audit your existing data assets, identify gaps, and define the AI opportunity that delivers the fastest measurable impact.",
      },
      {
        step: 2,
        title: "Data Preparation",
        description:
          "Clean, structure, and enrich your data. Quality in = quality out. We don't skip this step.",
      },
      {
        step: 3,
        title: "Model Development",
        description:
          "Build and train custom models — or fine-tune state-of-the-art foundation models — tailored precisely to your domain.",
      },
      {
        step: 4,
        title: "Rigorous Testing",
        description:
          "Validate accuracy, robustness, and bias resistance across real-world edge cases before a single line goes to production.",
      },
      {
        step: 5,
        title: "Deployment",
        description:
          "Deploy to cloud infrastructure with monitoring, auto-scaling, and zero-downtime rollouts.",
      },
      {
        step: 6,
        title: "Optimization",
        description:
          "Continuous model monitoring, retraining pipelines, and performance tuning as your data evolves.",
      },
    ],
    industries: [
      "Healthcare",
      "Finance & Banking",
      "E-commerce & Retail",
      "Education",
      "Real Estate",
      "Logistics",
      "Manufacturing",
      "Legal",
    ],
    href: "/services/ai-solutions",
  },
  {
    id: "web-development",
    slug: "web-development",
    title: "Web Development",
    shortTitle: "Web Dev",
    description:
      "We build high-performance web applications that convert visitors into customers and scale as your business grows. From lightning-fast marketing sites to complex SaaS platforms, every line of code is written with speed, security, and user experience as the non-negotiables.",
    shortDescription:
      "Performant, conversion-optimised web applications built for scale.",
    icon: "Globe",
    color: "#CC0000",
    features: [
      "Custom Web Application Development",
      "E-commerce Platforms",
      "SaaS Product Development",
      "Progressive Web Apps (PWA)",
      "API Development & Integration",
      "CMS Implementation",
      "Web Portals & Dashboards",
      "Landing Page Optimization",
      "Performance Optimization",
      "Security & Compliance",
    ],
    benefits: [
      "Sub-2s page loads that protect your SEO rankings and user retention",
      "Mobile-first designs that convert on every screen size",
      "Scalable architecture that grows with your traffic",
      "Built-in security to protect your users and your reputation",
      "Clean, documented code your team can actually maintain",
    ],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "AWS",
    ],
    process: [
      { step: 1, title: "Discovery", description: "Understand goals, users, and success metrics before writing a single line." },
      { step: 2, title: "Architecture", description: "Design a scalable technical blueprint: data models, API contracts, deployment strategy." },
      { step: 3, title: "UI/UX Design", description: "High-fidelity Figma designs validated against real user behavior patterns." },
      { step: 4, title: "Development", description: "Agile 2-week sprints with daily standups and weekly client demos." },
      { step: 5, title: "QA & Testing", description: "Cross-browser, cross-device, performance, and security testing before release." },
      { step: 6, title: "Launch & Support", description: "Zero-downtime deployment, monitoring dashboards, and 90-day post-launch support." },
    ],
    industries: ["E-commerce", "SaaS", "Healthcare", "Finance", "Education", "Real Estate"],
    href: "/services/web-development",
  },
  {
    id: "mobile-apps",
    slug: "mobile-apps",
    title: "Mobile App Development",
    shortTitle: "Mobile Apps",
    description:
      "Native-quality mobile experiences on iOS and Android, built faster and more cost-effectively with React Native and Flutter. We've shipped apps used by hundreds of thousands of users — and we know exactly what separates an app people love from one they delete after three minutes.",
    shortDescription:
      "iOS & Android apps that users love, built to App Store–ready standards.",
    icon: "Smartphone",
    color: "#CC0000",
    features: [
      "iOS App Development",
      "Android App Development",
      "Cross-Platform (React Native / Flutter)",
      "App Store Optimization (ASO)",
      "Push Notifications & Engagement",
      "Offline-First Architecture",
      "In-App Payments Integration",
      "Analytics & Crash Reporting",
      "App Modernization",
      "Wearable & IoT Apps",
    ],
    benefits: [
      "Ship to both platforms simultaneously, halving time-to-market",
      "Native performance with 60fps animations users expect",
      "Offline-capable architecture so your app works anywhere",
      "App Store-ready from day one — we know the review guidelines",
      "Crash monitoring and analytics built in, not bolted on",
    ],
    techStack: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "REST APIs", "GraphQL", "Redux", "Fastlane"],
    process: [
      { step: 1, title: "Product Definition", description: "Scope user stories, define MVP feature set, and align on KPIs before designing anything." },
      { step: 2, title: "UI/UX Design", description: "Mobile-native design patterns, gesture interactions, and platform-specific conventions." },
      { step: 3, title: "Development", description: "Component-driven development with continuous integration and automated builds." },
      { step: 4, title: "Beta Testing", description: "TestFlight / Play Console beta with real user feedback loops." },
      { step: 5, title: "App Store Submission", description: "We handle the entire submission process, including ASO metadata." },
      { step: 6, title: "Post-Launch", description: "Monitoring, crash analytics, and iterative updates based on usage data." },
    ],
    industries: ["Healthcare", "Fintech", "E-commerce", "Logistics", "Education", "On-Demand Services"],
    href: "/services/mobile-apps",
  },
  {
    id: "software-development",
    slug: "software-development",
    title: "Software Development",
    shortTitle: "Software Dev",
    description:
      "Custom software that solves the specific operational problems off-the-shelf products can't. We've built ERP systems, automation platforms, internal tools, and enterprise backends for companies across India and globally — always with clean architecture, thorough documentation, and a handover your team can maintain.",
    shortDescription:
      "Bespoke software engineered to eliminate your operational bottlenecks.",
    icon: "Code2",
    color: "#CC0000",
    features: [
      "Custom Enterprise Software",
      "ERP & CRM Development",
      "Internal Tools & Dashboards",
      "API Development & Integration",
      "Legacy System Modernization",
      "Workflow Automation",
      "Microservices Architecture",
      "Database Design & Optimization",
      "Third-Party Integrations",
      "Ongoing Maintenance & Support",
    ],
    benefits: [
      "Software shaped around your workflow — not the other way around",
      "Eliminate manual processes that drain your team's capacity",
      "Own your codebase outright — no vendor lock-in",
      "Architecture that scales from 10 to 10,000 concurrent users",
      "Full documentation and knowledge transfer at project close",
    ],
    techStack: ["Node.js", "Python", "FastAPI", "PostgreSQL", "MongoDB", "Redis", "Docker", "Kubernetes", "AWS", "Microservices"],
    process: [
      { step: 1, title: "Requirements", description: "Deep-dive workshops to map every business process and edge case before designing solutions." },
      { step: 2, title: "System Design", description: "Technical architecture, data models, integration points, and security framework." },
      { step: 3, title: "Agile Development", description: "2-week sprints, demo-driven progress, and constant communication." },
      { step: 4, title: "Integration Testing", description: "End-to-end, performance, and regression testing on every feature." },
      { step: 5, title: "UAT", description: "Your team tests in a production-mirror environment before we flip the switch." },
      { step: 6, title: "Deployment & Handover", description: "CI/CD pipeline setup, runbooks, and training sessions for your team." },
    ],
    industries: ["Manufacturing", "Finance", "Healthcare", "Logistics", "Real Estate", "Retail"],
    href: "/services/software-development",
  },
  {
    id: "cloud-devops",
    slug: "cloud-devops",
    title: "Cloud & DevOps",
    shortTitle: "Cloud & DevOps",
    description:
      "Modern infrastructure that ships faster, costs less, and never goes down when it matters most. We design and operate cloud environments on AWS, GCP, and Azure — with CI/CD pipelines, Kubernetes orchestration, observability stacks, and security postures that pass enterprise audits.",
    shortDescription:
      "Cloud infrastructure and DevOps pipelines engineered for zero-downtime delivery.",
    icon: "Cloud",
    color: "#CC0000",
    features: [
      "Cloud Migration & Strategy",
      "AWS / GCP / Azure Architecture",
      "Kubernetes & Container Orchestration",
      "CI/CD Pipeline Implementation",
      "Infrastructure as Code (Terraform)",
      "Observability & Monitoring",
      "Cost Optimization",
      "Security & Compliance (SOC 2, ISO 27001)",
      "Disaster Recovery Planning",
      "24/7 Infrastructure Support",
    ],
    benefits: [
      "Deploy up to 10x more frequently with automated CI/CD",
      "Reduce infrastructure costs 20–40% through rightsizing and reserved instances",
      "99.99% uptime SLA with multi-region failover",
      "Security-first posture with automated compliance reporting",
      "Full observability — know about issues before your users do",
    ],
    techStack: ["AWS", "GCP", "Azure", "Kubernetes", "Docker", "Terraform", "GitHub Actions", "Prometheus", "Grafana", "Datadog"],
    process: [
      { step: 1, title: "Infrastructure Audit", description: "Assess current state, identify risks, performance gaps, and cost inefficiencies." },
      { step: 2, title: "Cloud Strategy", description: "Design the target architecture: services, regions, redundancy, and security layers." },
      { step: 3, title: "Migration", description: "Phased, zero-downtime migration with rollback plans for every stage." },
      { step: 4, title: "CI/CD Setup", description: "Automated build, test, and deployment pipelines from commit to production." },
      { step: 5, title: "Observability", description: "Metrics, logging, tracing, and alerting so nothing happens in the dark." },
      { step: 6, title: "Ongoing Operations", description: "24/7 monitoring, incident response, and continuous cost optimization." },
    ],
    industries: ["SaaS", "E-commerce", "Finance", "Healthcare", "Media", "Enterprise"],
    href: "/services/cloud-devops",
  },
  {
    id: "data-analytics",
    slug: "data-analytics",
    title: "Data Analytics",
    shortTitle: "Data Analytics",
    description:
      "Your data already contains the answers to your biggest business questions. We build the pipelines, warehouses, and visualization layers that turn raw data into decisions your leadership team can act on in real time — not after a week of Excel gymnastics.",
    shortDescription:
      "Business intelligence and analytics platforms that turn raw data into revenue-driving decisions.",
    icon: "BarChart3",
    color: "#CC0000",
    features: [
      "Business Intelligence Dashboards",
      "Data Warehouse Design",
      "ETL / ELT Pipeline Development",
      "Real-Time Analytics",
      "Predictive Analytics",
      "Customer Segmentation",
      "Revenue & Churn Analysis",
      "Data Quality & Governance",
      "Self-Service Analytics Tools",
      "Data Strategy Consulting",
    ],
    benefits: [
      "Real-time dashboards your entire company can understand, not just data scientists",
      "Identify revenue leakage and growth opportunities in days, not quarters",
      "Automated reporting that frees your analysts for higher-value work",
      "Single source of truth — no more conflicting numbers in different spreadsheets",
      "Predictive models that tell you what's coming, not just what happened",
    ],
    techStack: ["Python", "dbt", "Apache Spark", "Snowflake", "BigQuery", "Tableau", "Power BI", "Airflow", "PostgreSQL", "Redshift"],
    process: [
      { step: 1, title: "Data Discovery", description: "Map all data sources, assess quality, and define the KPIs that drive real decisions." },
      { step: 2, title: "Architecture Design", description: "Design the data warehouse schema and pipeline architecture for scale." },
      { step: 3, title: "Pipeline Development", description: "Build robust ETL/ELT pipelines with automated monitoring and alerting." },
      { step: 4, title: "Dashboard Development", description: "Create interactive dashboards tailored to each stakeholder's decision needs." },
      { step: 5, title: "Training", description: "Enable your team to self-serve insights without relying on data engineers." },
      { step: 6, title: "Iteration", description: "Continuously evolve the data model as your business questions evolve." },
    ],
    industries: ["E-commerce", "Finance", "Healthcare", "SaaS", "Retail", "Manufacturing"],
    href: "/services/data-analytics",
  },
  {
    id: "ui-ux-design",
    slug: "ui-ux-design",
    title: "UI/UX Design",
    shortTitle: "UI/UX Design",
    description:
      "Design that doesn't just look exceptional — design that works. We create interfaces that users understand instinctively, navigate effortlessly, and return to repeatedly. Every pixel is justified by user research, business logic, or both.",
    shortDescription:
      "Human-centered design that drives engagement, retention, and conversion.",
    icon: "Palette",
    color: "#CC0000",
    features: [
      "UX Research & User Testing",
      "Information Architecture",
      "Wireframing & Prototyping",
      "UI Design (Figma)",
      "Design System Creation",
      "Interaction Design",
      "Mobile UI Design",
      "Accessibility Auditing",
      "Brand Identity Design",
      "Design-to-Code Handoff",
    ],
    benefits: [
      "Reduce development rework by 50%+ with validated designs before code",
      "Improve conversion rates with research-backed user flows",
      "Consistent design language across every product surface",
      "Accessibility-compliant designs that expand your addressable market",
      "Design systems that make future feature development 3x faster",
    ],
    techStack: ["Figma", "FigJam", "Maze", "Hotjar", "Storybook", "Lottie", "Principle", "Adobe XD", "Zeroheight", "Miro"],
    process: [
      { step: 1, title: "Research", description: "User interviews, competitive analysis, heuristic evaluation, and analytics deep-dive." },
      { step: 2, title: "Information Architecture", description: "Site maps, user flows, and content hierarchy before touching visual design." },
      { step: 3, title: "Wireframing", description: "Lo-fi wireframes validated with stakeholders before high-fidelity work begins." },
      { step: 4, title: "Visual Design", description: "High-fidelity Figma designs with a complete design system and component library." },
      { step: 5, title: "Prototyping & Testing", description: "Interactive prototypes tested with real users to catch issues before development." },
      { step: 6, title: "Handoff", description: "Developer-ready Figma files, annotated specs, and design tokens for seamless implementation." },
    ],
    industries: ["SaaS", "E-commerce", "Healthcare", "Fintech", "Education", "Enterprise"],
    href: "/services/ui-ux-design",
  },
];

export const getServiceBySlug = (slug: string): Service | undefined =>
  services.find((s) => s.slug === slug);

export const featuredServices = services.filter((s) =>
  ["ai-solutions", "web-development", "mobile-apps"].includes(s.slug)
);
